version: '3.4'

services:
  new-api:
    build: .
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      # 连接 MySQL 的核心密码
      - SQL_DSN=root:NovaApi_666888@tcp(db:3306)/new_api?charset=utf8mb4&parseTime=True&loc=Local
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
      - BATCH_UPDATE_ENABLED=true
      - NODE_NAME=nova-gateway-production
    depends_on:
      - db
    networks:
      - new-api-network

  db:
    image: mysql:8.0
    container_name: nova-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NovaApi_666888
      MYSQL_DATABASE: new_api
    #ports:
      # ⚠️ 仅在迁移期间临时开启本地端口映射
      #- "127.0.0.1:3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - new-api-network

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - "80:80"    # HTTP 端口
      - "443:443"  # HTTPS 安全端口 (这是绿锁的关键)
      - "81:81"    # NPM 后台管理端口
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - nova-network

networks:
  nova-network:
    driver: bridge